### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by ersitan** [cwi-swat/clair#14] opened 2020-05-11 07:14 UTC
Hi,

I have this error when I try to run it:

```
rascal>main(|file://C:/Users/user.name/Documents/ccflow/testfile.c|, true);
|lib://clair/lang/cpp/AST.rsc|(23833,193,<452,0>,<454,123>): Java("NullPointerException","")
        at lang.cpp.internal.Parser.getCommentsFromTranslationUnit(|unknown:///Parser.java|(0,0,<333,0>,<333,0>))
        at lang.cpp.internal.Parser.parseForComments(|unknown:///Parser.java|(0,0,<340,0>,<340,0>))
        at sun.reflect.NativeMethodAccessorImpl.invoke0(|unknown:///NativeMethodAccessorImpl.java|(0,0,<0,0>,<0,0>))
        at parseForComments(|lib://clair/lang/cpp/AST.rsc|(24022,2,<454,119>,<454,121>))
        at $root$(|prompt:///|(0,75,<1,0>,<1,75>))
ok

```

Win 10
Eclipse Version: 2020-03 (4.15.0)
rascal 0.17.0(Stable)
clair 0.1.0.202004301440

**Comment by rodinaarssen** [comment] 2020-05-11 07:50
Hi Ersitan.

I've fixed this just now. Thanks for the report!

**Comment by ersitan** [comment] 2020-05-11 07:57
Hi rodinaarssen,

I get this now. I am not sure if this is also a bug.

`rascal>main(|file://C:/Users/user.name/Documents/ccflow/testfile.c|, true);
|lib://clair/lang/cpp/AST.rsc|(23833,193,<452,0>,<454,123>): Java("NoSuchMethodError","org.rascalmpl.interpreter.IEvaluatorContext.getOutPrinter()Ljava/io/PrintWriter;")
        at lang.cpp.internal.CDTParser.<init>(|unknown:///CDTParser.java|(0,0,<134,0>,<134,0>))
        at lang.cpp.internal.Parser.parseForComments(|unknown:///Parser.java|(0,0,<339,0>,<339,0>))
        at sun.reflect.NativeMethodAccessorImpl.invoke0(|unknown:///NativeMethodAccessorImpl.java|(0,0,<0,0>,<0,0>))
        at parseForComments(|lib://clair/lang/cpp/AST.rsc|(24022,2,<454,119>,<454,121>))
        at $root$(|prompt:///|(0,75,<1,0>,<1,75>))
ok
rascal>`

**Comment by rodinaarssen** [comment] 2020-05-11 08:27
I see. This version of ClaiR depends on a feature in a more recent Rascal version. Later this week, a new stable Rascal version will be released, which ClaiR is compatible with. In the meantime, you could upgrade to our continuously released unstable repository (https://update.rascal-mpl.org/unstable).

**Comment by rodinaarssen** [comment] 2020-05-15 08:25
Rascal 0.18.0 has been released this week. If you update to that version (from https://update.rascal-mpl.org/stable), everything should work as intended. Please let me know if you still have issues!

**Closed by rodinaarssen** 2020-05-15 08:25 UTC
